model_params:
  n_estimators: 200
  min_samples_split: 7
  min_samples_leaf: 6
  max_depth: 10
  criterion: entropy
  random_state: 101

model_selection:
  model_name: RandomForestClassifier
  model_score: 0.6
